#!/bin/bash -l
#SBATCH -N 1          # you'll never need more than 1 node for the serial code
#SBATCH -t 00:10:00   # adjust the amount of time as necessary
#SBATCH -J binned
#SBATCH -o binned.%j.stdout
#SBATCH -e binned.%j.error
#SBATCH -p normal 
#SBATCH -n 1
 
./binned -n 500 -o binned.txt

