#!/bin/bash -l
#SBATCH -N 1          # you'll never need more than 1 node for the openmp code
#SBATCH -t 00:10:00   # adjust the amount of time as necessary
#SBATCH -J openmp32
#SBATCH -o openmp32.%j.stdout
#SBATCH -e openmp32.%j.error
#SBATCH -n 1  
#SBATCH -p development

export OMP_NUM_THREADS=24
#export OMP_PLACES=cores
./openmp -n 500 -o openmp.txt
